Poodle-E-Learning-Platform/ViewModels/Course/DetailsViewModel.cs
using Poodle_e_Learning_Platform.InputModels.Section;
using Poodle_e_Learning_Platform.ViewModels.Sections;
using Poodle_e_Learning_Platform.ViewModels.Student;
using System;
using System.Collections.Generic;

namespace Poodle_e_Learning_Platform.ViewModels.Course
{
    public class DetailsViewModel
    {
        public int Id { get; set; }

        public string Title { get; set; }

        public string Description { get; set; }

        public DateTime StartDate { get; set; }

        public DateTime EndDate { get; set; }

        public bool IsPrivate { get; set; }

        public SectionInputModel SectionInputModel { get; set; }

        public IEnumerable<SectionViewModel> Sections { get; set; }
    }
}

Poodle-E-Learning-Platform/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Poodle_e_Learning_Platform.Data;
using Poodle_e_Learning_Platform.Globals;
using Poodle_e_Learning_Platform.InputModels.Course;
using Poodle_e_Learning_Platform.Models;
using Poodle_e_Learning_Platform.Services.Contracts;
using Poodle_e_Learning_Platform.ViewModels.Course;
using Poodle_e_Learning_Platform.ViewModels.Home;
using Poodle_e_Learning_Platform.ViewModels.Student;

namespace Poodle_e_Learning_Platform.Controllers
{
    public class CoursesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ICoursesService coursesService;
        private readonly IEnrollmentService enrollmentService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IApplicationUserService applicationUserService;

        public CoursesController(ApplicationDbContext context, 
            ICoursesService coursesService, 
            IEnrollmentService enrollmentService, 
            IApplicationUserService applicationUserService,
            UserManager<ApplicationUser> userManager)
        {
            _context = context;
            this.userManager = userManager;
            this.coursesService = coursesService;
            this.enrollmentService = enrollmentService;
            this.applicationUserService = applicationUserService;
        }

        // GET: Courses
        [Authorize]
        public async Task<IActionResult> Index(int page, string orderBy = "")
        {
            ApplicationUser current = userManager.Users.FirstOrDefault(u => u.Id == int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)));

            if (current is not null && await userManager.IsInRoleAsync(current, "Student")) 
            {
                return RedirectToAction(nameof(StudentCourses), new { studentId = current.Id });
            }

            var applicationDbContext = _context.Courses.Select(c => c);//.Include(c => c.ApplicationUser);


            IEnumerable<Course> courses = await applicationDbContext.ToListAsync();

            if (!string.IsNullOrEmpty(orderBy)) 
            {
                if (orderBy.ToLower() == "enddate")
                {
                    courses = await _context.Courses.Select(c => c).OrderBy(c => c.EndDate).ToListAsync();
                }

                if (orderBy.ToLower() == "startdate")
                {
                    courses = await _context.Courses.Select(c => c).OrderBy(c => c.StartDate).ToListAsync();
                }

                if (orderBy.ToLower() == "created")
                {
                    courses = await _context.Courses.Select(c => c).OrderBy(c => c.Created).ToListAsync();
                }

                if (orderBy.ToLower() == "title") 
                {
                    courses = await _context.Courses.Select(c => c).OrderBy(c => c.Title).ToListAsync();
                }

                if (orderBy.ToLower() == "description")
                {
                    courses = await _context.Courses.Select(c => c).OrderBy(c => c.Description).ToListAsync();
                }

                if (orderBy.ToLower() == "isprivate")
                {
                    courses = await _context.Courses.Select(c => c).OrderBy(c => c.IsPrivate).ToListAsync();
                }
            }
            return View(courses);
        }

        // GET: Courses/Details/5
        [Authorize]
        public IActionResult Details(int id)
        {
            int userId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            if (coursesService.IsPrivate(id))
            {
                if (!User.IsInRole("Teacher") && !enrollmentService.IsEnrolled(userId, id))
                {
                    return View("Error", new ErrorViewModel() { RequestId = "Access denied!" });
                }
            }


            if (!enrollmentService.IsEnrolled(userId, id) && !User.IsInRole("Teacher"))
            {
                enrollmentService.Create(userId, id);
            }


            DetailsViewModel course = coursesService.GetCourseDetails(id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // GET: Courses/Create

        [Authorize(Roles = "Teacher")]
        public IActionResult Create()
        {
            ViewData["ApplicationUserId"] = new SelectList(_context.Users, "Id", "FirstName");
            return View();
        }

        // POST: Courses/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Teacher")]
        public IActionResult Create(CourseInputModel inputModel)
        {

            if (coursesService.Exists(inputModel.Title))
            {
                ModelState.AddModelError("Title", "There is already a course with the spacified name");
            }

            if (!ModelState.IsValid)
            {
                return View(inputModel);
            }

            coursesService.Create(inputModel);

            return RedirectToAction(nameof(Index));
        }

        // GET: Courses/Edit/5
        [Authorize(Roles = "Teacher")]
        public IActionResult Edit(int id)
        {
            EditCourseInputModel editCourse = coursesService.GetEditCourse(id);
            return View(editCourse);
        }

        // POST: Courses/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Teacher")]
        public IActionResult Edit(EditCourseInputModel inputModel)
        {
            if (!ModelState.IsValid) 
            {
                return View(inputModel);
            }

            coursesService.Edit(inputModel);

            return RedirectToAction(nameof(Index));

        }

        // GET: Courses/Delete/5
        [Authorize(Roles = "Teacher")]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            coursesService.Delete((int)id);


            return RedirectToAction("index", "Home");
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Teacher")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var course = await _context.Courses.FindAsync(id);
            _context.Courses.Remove(course);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CourseExists(int id)
        {
            return _context.Courses.Any(e => e.Id == id);
        }

        [Authorize]
        public async Task<IActionResult> StudentCourses(int studentId, int page = 1) 
        {
            var user = userManager.Users.FirstOrDefault(u => u.Id == studentId);

            if (user is not null && await userManager.IsInRoleAsync(user, "Teacher")) 
            {
                return RedirectToAction(nameof(Index));
            }

            IndexViewModel viewModel = coursesService
                .GetStudentIndexPage(studentId, page, User.Identity.IsAuthenticated);
            return View(viewModel);
        }
    }
}

Poodle-E-Learning-Platform/Controllers/SectionsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Poodle_e_Learning_Platform.InputModels.Section;
using Poodle_e_Learning_Platform.Models;
using Poodle_e_Learning_Platform.Services.Contracts;
using Poodle_e_Learning_Platform.ViewModels.Sections;
using System;
using System.Security.Claims;
using System.Linq;
using System.Threading.Tasks;

namespace Poodle_e_Learning_Platform.Controllers
{
    [Authorize]
    public class SectionsController : Controller
    {
        private readonly IEnrollmentService enrollmentService;
        private readonly ISectionsService sectionsService;
        private readonly IVideoServise videoServise;
        private readonly UserManager<ApplicationUser> userManager;

        public SectionsController(
            IEnrollmentService enrollmentService, 
            ISectionsService sectionsService, 
            IVideoServise videoServise,
            UserManager<ApplicationUser> userManager)
        {
            this.enrollmentService = enrollmentService;
            this.sectionsService = sectionsService;
            this.videoServise = videoServise;
            this.userManager = userManager;
        }

        [HttpPost]
        [Authorize(Roles = "Teacher")]
        public IActionResult Create(SectionInputModel inputModel)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Details", "Courses", new { id = inputModel.CourseId });
            }

            sectionsService.Create(inputModel);

            return RedirectToAction("Details", "Courses", new { id = inputModel.CourseId });
        }

        [HttpGet]
        [Authorize(Roles = "Teacher")]
        public IActionResult Delete(int id, string returnCourseId)
        {
            sectionsService.Delete(id);

            return RedirectToAction("Details", "Courses", new { id = returnCourseId });
        }

        [Authorize(Roles = "Teacher")]
        public IActionResult Edit(int id) 
        {
            EditSectionInputModel model = sectionsService.GetEditSectionData(id);
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Teacher")]
        public IActionResult Edit(EditSectionInputModel inputModel)
        {
            if (!ModelState.IsValid)
            {
                return View(inputModel);
            }

            sectionsService.Update(inputModel);
            return RedirectToAction("Details", "Courses", new { id = inputModel.CourseId });
        }

        public async Task<IActionResult> Details(int id)
        {
            ApplicationUser user = userManager.Users.FirstOrDefault(u => u.Id == int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)));
            videoServise.GetAllVideos();
            if (await userManager.IsInRoleAsync(user, "Student"))
            {
                int courseId = sectionsService.GetCourseIdBySectionId(id);

                if (!enrollmentService.IsEnrolled(user.Id, courseId)) 
                {
                    return RedirectToAction("Index", "Courses");
                }
            }

            SectionViewModel model = sectionsService.GetSectionDetails(id);
            return View(model);
        }
    }
}

Poodle-E-Learning-Platform/Views/Courses/Create.cshtml
@using System.Security.Claims
@model Poodle_e_Learning_Platform.InputModels.Course.CourseInputModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Course</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            

            <div class="form-group">
                <label asp-for="@Model.IsPrivate" class="form-label"></label>
                <input asp-for="@Model.IsPrivate" />
            </div>
            <div class="form-group">
                <label asp-for="@Model.StartDate" class="control-label"></label>
                <input asp-for="@Model.StartDate" class="form-control" />
                <span asp-validation-for="@Model.StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.EndDate" class="control-label"></label>
                <input asp-for="@Model.EndDate" class="form-control" />
                <span asp-validation-for="@Model.EndDate" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="@Model.ApplicationUserId" value="@User.FindFirstValue(ClaimTypes.NameIdentifier)"/>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-info" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

Poodle-E-Learning-Platform/Views/Courses/Delete.cshtml
@model Poodle_e_Learning_Platform.Models.Course

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Course</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ApplicationUser)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ApplicationUser.FirstName)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsPrivate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsPrivate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsStudentEnrolled)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsStudentEnrolled)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Created)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Poodle-E-Learning-Platform/Views/Courses/Details.cshtml
@using System.Security.Claims
@model Poodle_e_Learning_Platform.ViewModels.Course.DetailsViewModel

@{
    ViewData["Title"] = "Details";
}

@*<h1>Details</h1>*@

<div>
    <div class="container">
        <div class="row">
            <div class="col">
                <h1>Course details</h1>
            </div>
            @if (!userService.IsTeacher(int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier))))
            {
                <div class="col">
                    <button style="position:center; right:0px;" class="btn btn-warning"><a asp-controller="Enrollment" asp-action="UnenrollStudent" asp-route-userId="@User.FindFirstValue(ClaimTypes.NameIdentifier)" asp-route-courseId="@Model.Id">Unenroll</a> </button>

                </div>
            }


        </div>

    </div>

    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
    </dl>
</div>

<h2>Content</h2>

<div class="row">
    @foreach (var sectionItem in Model.Sections)
    {
        <div class="col-sm-6" style="margin-top:1%">
            <div class="card">
                <div class="card-body">

                    @if (@Model.StartDate > DateTime.Now)
                    {
                        <h5 class="card-title">@sectionItem.Title</h5>
                        <p>This resourse will be open on: @Model.StartDate.ToString("dd.MM.yyyy")</p>
                    }
                    else
                    {
                        <a asp-controller="Sections" asp-action="Details" asp-route-id="@sectionItem.Id"><h5 class="card-title">@sectionItem.Title</h5></a>    
                    }

                    @if (User.Identity.IsAuthenticated)
                    {
                        @if (userService.IsTeacher(int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier))))
                        {
                            <a class="btn btn-danger" asp-controller="Sections" asp-action="Delete" asp-route-id="@sectionItem.Id" asp-route-returnCourseId="@Model.Id"><small>delete</small></a>
                            <a class="btn btn-warning" asp-controller="Sections" asp-action="Edit" asp-route-id="@sectionItem.Id"><small>Edit</small></a>
                        }
                    }
                </div>
            </div>
        </div>
    }

</div>
@{
    /*
<div class="row">
    <div style="display:grid; grid-template-columns:1fr 1fr 1fr;">
        <div style="background-color:black;"></div>
        <div style="background-color:gray;">
            <nav aria-label="...">
                <ul class="pagination">
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1">Previous</a>
                    </li>
                    <li class="page-item"><a class="page-link" href="#">1</a></li>
                    <li class="page-item active">
                        <a class="page-link" href="#">2 <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                    <li class="page-item">
                        <a class="page-link" href="#">Next</a>
                    </li>
                </ul>
            </nav>
        </div>
        <div style="background-color:red;"></div>
    </div>
</div>
*/
}
<div>
    @if (User.Identity.IsAuthenticated)
    {
        @if (userService.IsTeacher(int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier))))
        {
            <a class="btn btn-warning" asp-action="Edit" asp-route-id="@Model.Id">Edit</a>

            @if (Model.IsPrivate)
            {
                <a class="btn btn-success" asp-controller="Enrollment" asp-action="GetEnroll" asp-route-courseId="@Model.Id">Entroll students</a>
            }
        }
    }

    <a class="btn btn-info"  asp-action="Index">Back to List</a>
</div>
@if (User.Identity.IsAuthenticated)
{
    //to get Id of user
    @if (userService.IsTeacher(int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier))))
    {
        <div asp-validation-summary=All>
        </div>

        <form asp-controller="Sections" asp-action="Create" type="post">
            <div class="form-group">
                <div class="form-group">
                    <label asp-for="@Model.SectionInputModel.Title"></label>
                    <input asp-for="@Model.SectionInputModel.Title" name="title" id="title" class="form-control" />
                    <div class="text-danger">
                        <span asp-validation-for="@Model.SectionInputModel.Title"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.SectionInputModel.Content"></label>
                    <input asp-for="@Model.SectionInputModel.Content" id="content" name="content" class="form-control" />
                    <div class="text-danger">
                        <span asp-validation-for="@Model.SectionInputModel.Content"></span>
                    </div>
                </div>
                <input type="hidden" id="courseId" name="courseId" value="@Model.Id" />
            </div>

            <button class="btn btn-success" type="submit">Create section</button>
        </form>
    }
}
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

Poodle-E-Learning-Platform/Views/Courses/Edit.cshtml
@model Poodle_e_Learning_Platform.Models.Course

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Course</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ApplicationUserId" class="control-label"></label>
                <select asp-for="ApplicationUserId" class="form-control" asp-items="ViewBag.ApplicationUserId"></select>
                <span asp-validation-for="ApplicationUserId" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsPrivate" /> @Html.DisplayNameFor(model => model.IsPrivate)
                </label>
            </div>
            <div class="form-group form-check">
                @*<label class="form-check-label">
                    <input class="form-check-input" asp-for="IsStudentEnrolled" /> @Html.DisplayNameFor(model => model.IsStudentEnrolled)
                </label>*@
            </div>
            <div class="form-group">
                <label asp-for="Created" class="control-label"></label>
                <input asp-for="Created" class="form-control" />
                <span asp-validation-for="Created" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-danger" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-info" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Poodle-E-Learning-Platform/Views/Courses/Index.cshtml
@using System.Security.Claims
@model IEnumerable<Poodle_e_Learning_Platform.Models.Course>

@{
    ViewData["Title"] = "Index";
}

<h1>Courses</h1>

@if (userService.IsTeacher(int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier))))
{
    <p>
        <a class="btn btn-success" asp-action="Create">Create New Course</a>
    </p>
}
<table class="table">
    <thead>
        <tr>
            <th>
                <a asp-controller="Courses" asp-action="Index" asp-route-orderBy="title">@Html.DisplayNameFor(model => model.Title)</a>
            </th>

            <th>
                <a asp-controller="Courses" asp-action="Index" asp-route-orderBy="Description">@Html.DisplayNameFor(model => model.Description)</a>
            </th>

            @if (userService.IsTeacher(int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier))))
            {
                <th>
                    <a asp-controller="Courses" asp-action="Index" asp-route-orderBy="IsPrivate">@Html.DisplayNameFor(model => model.IsPrivate)</a>
                </th>
                <th>
                    <a asp-controller="Courses" asp-action="Index" asp-route-orderBy="Created">@Html.DisplayNameFor(model => model.Created)</a>
                </th>
            }

            <th>
                <a asp-controller="Courses" asp-action="Index" asp-route-orderBy="StartDate">@Html.DisplayNameFor(model => model.StartDate)</a>
            </th>
            <th>
                <a asp-controller="Courses" asp-action="Index" asp-route-orderBy="EndDate">@Html.DisplayNameFor(model => model.EndDate)</a>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            @if (userService.IsTeacher(int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier))))
            {
                <tr>

                    <td>
                        <a asp-controller="Courses" asp-action="Details" asp-route-id="@item.Id">@item.Title</a>
                    </td>
                    <td>
                        <a asp-controller="Courses" asp-action="Details" asp-route-id="@item.Id">@item.Description</a>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IsPrivate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Created)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.StartDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EndDate)
                    </td>
                    <td>
                        <a style="width: 80px; margin:2%;" class="btn btn-warning" asp-action="Edit" asp-route-id="@item.Id">Edit</a> 
                        <a style="width: 80px; margin:2%;" class="btn btn-dark" asp-action="Details" asp-route-id="@item.Id">Details</a> 
                        <a style="width: 80px; margin:2%;" class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id">Delete</a>

                    </td>
                </tr>

            }
            else
            {
                //added end date check about courses for students
                @if (item.EndDate > DateTime.Now)
                {
                    <tr>

                        <td>
                            <a asp-controller="Courses" asp-action="Details" asp-route-id="@item.Id">@item.Title</a>
                        </td>
                        <td>
                            <a asp-controller="Courses" asp-action="Details" asp-route-id="@item.Id">@item.Description</a>
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.StartDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.EndDate)
                        </td>

                    </tr>
                }
            }
        }
    </tbody>
</table>

@*<script>
    window.onload = function() {
        let body = document.getElementsByTagName('body')[0];
        body.style.backgroundImage = 'C:\Desktop\Poodle e-Learning Platform\Poodle e-Learning Platform\wwwroot\Pictures\img2.png';
    }
</script>*@