Poodle-E-Learning-Platform/Controllers/ApplicationUsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Poodle_e_Learning_Platform.Data;
using Poodle_e_Learning_Platform.InputModels.ApplicationUser;
using Poodle_e_Learning_Platform.Models;
using Poodle_e_Learning_Platform.Services.Contracts;
using Poodle_e_Learning_Platform.ViewModels.ApplicationUsers;

namespace Poodle_e_Learning_Platform.Controllers
{
    public class ApplicationUsersController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IApplicationUserService userService;
        private readonly UserManager<ApplicationUser> userManager;

        public ApplicationUsersController(ApplicationDbContext context, IApplicationUserService userService, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            this.userService = userService;
            this.userManager = userManager;
        }

        // GET: ApplicationUsers
        [Authorize(Roles = "Teacher")]
        public IActionResult Index()
        {
            IEnumerable<ApplicationUserViewModel> model = userService.GetAllUsers();

            return View(model);           
        }

        // GET: ApplicationUsers/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int id)
        {
            ApplicationUser currentUser = await userManager.GetUserAsync(User);

            if (!await userManager.IsInRoleAsync(currentUser, "Teacher"))
            {

                if (currentUser.Id != id)
                {
                    ErrorViewModel error = new ErrorViewModel()
                    {
                        RequestId = "Unauthorized",
                    };
                    return View("NoAccess", error);//test 
                }
            }

            ApplicationUserViewModel model = userService.GetUserDetails(id);

            return View(model);
        }

        // GET: ApplicationUsers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ApplicationUsers/Create
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FirstName,LastName,ProfilePicture,Id,UserName,NormalizedUserName,Email,NormalizedEmail,EmailConfirmed,PasswordHash,SecurityStamp,ConcurrencyStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEnd,LockoutEnabled,AccessFailedCount")] ApplicationUser applicationUser)
        {
            if (ModelState.IsValid)
            {
                _context.Add(applicationUser);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(applicationUser);
        }

        // GET: ApplicationUsers/Edit/5
        [Authorize]
        public IActionResult Edit(int id)
        {
            int currentUserId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));

            if (currentUserId != id)
            {
                ErrorViewModel errorModel = new ErrorViewModel
                {
                    RequestId = "Unauthorized",
                };

                return View("NoAccess", errorModel);
            }

            var applicationUser = userService.ApplicationUserData(id);
            if (applicationUser == null)
            {
                return NotFound();
            }
            return View(applicationUser);
        }

        // POST: ApplicationUsers/Edit/5
       
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ApplicationUserInputModel inputModel)
        {
            if (!ModelState.IsValid) 
            {
                return View(inputModel);
            }

            int currentUserId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));

            if (currentUserId != inputModel.Id)
            {
                ErrorViewModel errorModel = new ErrorViewModel
                {
                    RequestId = "Unauthorized",
                };

                return View("NoAccess", errorModel);
            }

            userService.EditUser(inputModel);

            if (userService.IsTeacher(inputModel.Id))
            {
                return RedirectToAction(nameof(Index));
            };

            return RedirectToAction(nameof(Details), new { id = inputModel.Id });
        }

        // GET: ApplicationUsers/Delete/5
        public IActionResult Delete(int id)
        {
             userService.Delete(id);

            return  RedirectToAction(nameof(Index));
        }

        // POST: ApplicationUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var applicationUser = await _context.Users.FindAsync(id);
            _context.Users.Remove(applicationUser);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ApplicationUserExists(int id)
        {
            return _context.Users.Any(e => e.Id == id);
        }
    }
}

Poodle-E-Learning-Platform/Views/Shared/NoAccess.cshtml
@{
    Layout = "";

}




<style>
    body {
        background-image: url('../../Pictures/img2.png');
        background-size: 2000px 1000px;
        background-repeat: no-repeat;
        background-attachment: fixed;
    }
</style>



<head>
    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">
    <link href="~/fonts/icomoon/dinostyle.css" rel="stylesheet" />
</head>
<body>
    
        <img src="~/images/testlogo.png" alt="Alternate Text" />
        <a class="message" href="/home">
            You are not authorized.
        </a>

        
        <div class="container">
            <div class="neon">403</div>
            <div class="door-frame">
                <div class="door">
                    <div class="rectangle">
                    </div>
                    <div class="handle">
                    </div>
                    <div class="window">
                        <div class="eye">
                        </div>
                        <div class="eye eye2">
                        </div>
                        <div class="leaf">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    
</body>

Poodle-E-Learning-Platform/Views/Shared/_Layout.cshtml
@using System.Security.Claims
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" href="~/images/testlogo.png" type="image/icon type"> <!--test favicon-->
    <title>@ViewData["Title"] - Poodle_e_Learning_Platform</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <!--
    <link rel="stylesheet" href="~/css/site.css" />
    -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500&display=swap" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Source+Serif+Pro:400,600&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="~/fonts/icomoon/style.css">

    <link rel="stylesheet" href="~/css/owl.carousel.min.css">

    <!-- Bootstrap CSS
    <link rel="stylesheet" href="~/css/bootstrap.min.css">
     -->
    <!-- Style -->
    <link rel="stylesheet" href="~/fonts/icomoon/astyle.css">

    <style>
        body {
            background-image: url('../../Pictures/img2.png');
            background-size: 2000px 1000px;
            background-repeat: no-repeat;
            background-attachment: fixed;
        }
    </style>
       
   
</head>
<body>
    

    <aside class="sidebar">
        <div class="toggle">
            <a href="#" class="burger js-menu-toggle" data-toggle="collapse" data-target="#main-navbar">
                <span></span>
            </a>
        </div>
        <div class="side-inner">

            <a asp-controller="Home" asp-action="Index"><img src="~/images/testlogo.png" style="width: 4rem;" alt=""></a>


            <div class="search-form">
                <form action="#">
                    <span class="wrap-icon">
                        <span class="icon-search2"></span>
                    </span>

                </form>
            </div>
            <div class="nav-menu">
                <ul>
                    <partial name="_LoginPartial" />
                    <!--<li><span class="wrap-icon icon-user mr-3"><partial name="_LoginPartial" /></span></li> ???????-->
                    <!--
                    <li><a asp-controller="ApplicationUsers" asp-action="Edit" class="d-flex align-items-center"><span class="wrap-icon icon-user mr-3"></span><span class="menu-text">Edit Profile</span></a></li>
                    -->
                    <li><a title="Home" asp-controller="Home" asp-action="Index" class="d-flex align-items-center"><span class="wrap-icon icon-home mr-3"></span><span class="menu-text">Home</span></a></li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a title="Courses" asp-controller="Courses" asp-action="Index" class="d-flex align-items-center"><span class="wrap-icon icon-list2 mr-3"></span><span class="menu-text">Courses</span></a></li>
                    }
                    @if (User.Identity.IsAuthenticated)
                    {
                        @if (userService.IsTeacher(int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier))))
                        {
                            <li>
                                <a title="Students" asp-controller="ApplicationUsers" asp-action="Index" class="d-flex align-items-center"><span class="wrap-icon icon-group mr-3 mr-3"></span><span class="menu-text">Students</span></a>
                            </li>
                        }

                        <li>
                            <a title="Logout" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" }) class="d-flex align-items-center"><span class="wrap-icon icon-power-off mr-3"></span><span class="menu-text">Sign Out</span></a>
                        </li>
                    }
                </ul>
            </div>
        </div>

    </aside>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()

           
           
            
        </main>

    </div>
    

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/fonts/icomoon/jquery-3.3.1.min.js"></script>
    <script src="~/fonts/icomoon/popper.min.js"></script>
    <script src="~/fonts/icomoon/bootstrap.min.js"></script>
    <script src="~/fonts/icomoon/main.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>